blank_issues_enabled: true
contact_links:
  - name: ":question: Comment, Question or Problem"
    url: https://github.com/microsoft/msquic/discussions
    about: Please direct general discussion here.
