blank_issues_enabled: true
contact_links:
  - name: Comment, Question or Problem
    url: https://github.com/microsoft/msquic/discussions
    about: Please direct general discussion here.
  - name: Report a security vulnerability
    url: https://msrc.microsoft.com/create-report
    about: Please report security vulnerabilities here.
